CONNECT student/student;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE orderdetails CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE payments CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE orders CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE customers CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE employees CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE offices CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE products CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE productlines CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/


CREATE TABLE productlines (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY(
    start with 1 increment by 1
  ),
  productLine VARCHAR2(50),
  textDescription VARCHAR2(4000),
  htmlDescription CLOB,
  image BLOB,
  CONSTRAINT pk_productlines PRIMARY KEY (id)
);

CREATE TABLE products (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY(
    start with 1 increment by 1
  ),
  productCode VARCHAR2(15),
  productName VARCHAR2(70) NOT NULL,
  productLine NUMBER NOT NULL,
  productScale VARCHAR2(10) NOT NULL,
  productVendor VARCHAR2(50) NOT NULL,
  productDescription CLOB NOT NULL,
  quantityInStock NUMBER(6) NOT NULL,
  buyPrice NUMBER(10,2) NOT NULL,
  MSRP NUMBER(10,2) NOT NULL,
  CONSTRAINT pk_products PRIMARY KEY (id),
  CONSTRAINT fk_products_line FOREIGN KEY (productLine)
    REFERENCES productlines(id)
);

CREATE TABLE offices (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY(
    start with 1 increment by 1
  ),
  officeCode VARCHAR2(10),
  city VARCHAR2(50) NOT NULL,
  phone VARCHAR2(50) NOT NULL,
  addressLine1 VARCHAR2(50) NOT NULL,
  addressLine2 VARCHAR2(50),
  state VARCHAR2(50),
  country VARCHAR2(50) NOT NULL,
  postalCode VARCHAR2(15) NOT NULL,
  territory VARCHAR2(10) NOT NULL,
  CONSTRAINT pk_offices PRIMARY KEY (id)
);

CREATE TABLE employees (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY(
    start with 1 increment by 1
  ),
  employeeNumber NUMBER,
  lastName VARCHAR2(50) NOT NULL,
  firstName VARCHAR2(50) NOT NULL,
  extension VARCHAR2(10) NOT NULL,
  email VARCHAR2(100) NOT NULL,
  officeCode NUMBER NOT NULL,
  reportsTo NUMBER,
  jobTitle VARCHAR2(50) NOT NULL,
  CONSTRAINT pk_employees PRIMARY KEY (id),
  CONSTRAINT fk_emp_manager FOREIGN KEY (reportsTo)
    REFERENCES employees(id),
  CONSTRAINT fk_emp_office FOREIGN KEY (officeCode)
    REFERENCES offices(id)
);

CREATE TABLE customers (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY(
    start with 1 increment by 1
  ),
  customerNumber NUMBER,
  customerName VARCHAR2(50) NOT NULL,
  contactLastName VARCHAR2(50) NOT NULL,
  contactFirstName VARCHAR2(50) NOT NULL,
  phone VARCHAR2(50) NOT NULL,
  addressLine1 VARCHAR2(50) NOT NULL,
  addressLine2 VARCHAR2(50),
  city VARCHAR2(50) NOT NULL,
  state VARCHAR2(50),
  postalCode VARCHAR2(15),
  country VARCHAR2(50) NOT NULL,
  salesRepEmployeeNumber NUMBER,
  creditLimit NUMBER(10,2),
  CONSTRAINT pk_customers PRIMARY KEY (id),
  CONSTRAINT fk_customers_emp FOREIGN KEY (salesRepEmployeeNumber)
    REFERENCES employees(id)
);

CREATE TABLE payments (
  customerId NUMBER,
  checkNumber VARCHAR2(50) NOT NULL,
  paymentDate DATE NOT NULL,
  amount NUMBER(10,2) NOT NULL,
  CONSTRAINT pk_payments PRIMARY KEY (customerId, checkNumber),
  CONSTRAINT fk_payments_customer FOREIGN KEY (customerId)
    REFERENCES customers(id)
);

CREATE TABLE orders (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY(
    start with 1 increment by 1
  ),
  orderNumber NUMBER,
  orderDate DATE NOT NULL,
  requiredDate DATE NOT NULL,
  shippedDate DATE,
  status VARCHAR2(15) NOT NULL,
  comments CLOB,
  customerNumber NUMBER NOT NULL,
  CONSTRAINT pk_orders PRIMARY KEY (id),
  CONSTRAINT fk_orders_customer FOREIGN KEY (customerNumber)
    REFERENCES customers(id)
);

CREATE TABLE orderdetails (
  orderId NUMBER,
  productId NUMBER NOT NULL,
  quantityOrdered NUMBER NOT NULL,
  priceEach NUMBER(10,2) NOT NULL,
  orderLineNumber NUMBER(6) NOT NULL,
  CONSTRAINT pk_orderdetails PRIMARY KEY (orderId, productId),
  CONSTRAINT fk_od_order FOREIGN KEY (orderId)
    REFERENCES orders(id),
  CONSTRAINT fk_od_product FOREIGN KEY (productId)
    REFERENCES products(id)
);