services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: student-ora-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=topsecret
    volumes:
      - c:/Users/kacper.lizewski/.docker/customVolumes/ora-student-db:/opt/oracle/oradata
    restart: unless-stopped

volumes:
  oracle-data:
    driver: local