CREATE TABLESPACE STUDENT_TABSPACE
DATAFILE '/opt/oracle/oradata/student_tabspace.dbf' SIZE 100M
AUTOEXTEND ON
NEXT 50M
MAXSIZE UNLIMITED;

CREATE USER student IDENTIFIED BY student
DEFAULT TABLESPACE student_tabspace
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON student_tabspace;

GRANT CONNECT, RESOURCE TO student;
GRANT CREATE SESSION TO student;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO student;
GRANT CREATE PROCEDURE, CREATE TRIGGER TO student;

COMMIT;